name: Var test

on:
  push

jobs:
  basic-job:
    runs-on: [macos-latest, ubuntu-latest]
    steps:
      - name: Test linux
        if: ${{ runner.os }} == Linux
        run: 'echo "Siamo su Linux!!"'

      - name: Test mac
        if: ${{ runner.os }} == macOS
        run: 'echo "Siamo su mac!!"'
